
-- MÓDULO 04: CRIANDO TABELAS

-- AULA 03: CRIANDO A TABELA DE CLIENTES
CREATE TABLE [TABELA DE CLIENTES]
([CPF] [VARCHAR] (11),
[NOME] [VARCHAR] (100),
[ENDERECO 1] [VARCHAR] (150),
[ENDERECO 2] [VARCHAR] (150),
[BAIRRO] [VARCHAR] (50),
[CIDADE] [VARCHAR] (50),
[ESTADO] [VARCHAR] (2),
[CEP] [VARCHAR] (8),
[DATA DE NASCIMENTO] [DATE],
[IDADE] [SMALLINT],
[SEXO] [VARCHAR] (1),
[LIMITE DE CREDITO] [MONEY],
[VOLUME DE COMPRA] [FLOAT],
[PRIMEIRA COMPRA] [BIT])


-- MÓDULO 05: MANUTENÇÃO DOS DADOS NA TABELA

-- AULA 02: INSERINDO DADOS NA TABELA DE PRODUTOS 
INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],
[NOME DO PRODUTO],
[EMBAlAGEM],
[TAMANHO],
[SABOR],
[PREÇO DE LISTA])

VALUES
('1040107',
'Light - 350 ml - Melância',
'Lata',
'350 ml',
'Melancia',
4.56)

-- AULA 03: EXERCICIO - INCLUINDO O PRIMEIRO VENDEDOR:
INSERT INTO [TABELA DE VENDEDORES]
(MATRICULA,
NOME,
[PERCENTUAL COMISSAO])

VALUES
('00235',
'Márcio Almeida Silva',
0.08)

INSERT INTO [TABELA DE VENDEDORES]
(MATRICULA,
NOME,
[PERCENTUAL COMISSAO])

VALUES
('00236',
'Cláudia Morais',
0.08)

-- AULA 04 E 05: INCLUINDO VARIOS REGISTROS
INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],
[NOME DO PRODUTO],
EMBALAGEM,
TAMANHO,
SABOR,
[PREÇO DE LISTA])

VALUES
('1037797','Clean - 2 Litros - Laranja', 'PET', '2 Litros', 'Laranja', 16.01),
('1000889',	'Sabor da Montanha - 700 ml - Uva', 'Garrafa','700 ml', 'Uva',	6.31);

-- AULA 08: ALTERANDO REGISTROS
-- VAMOS INSERIR OS REGISTROS QUE SERÃO ALTERADOS DEPOIS
INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA])
VALUES
('544931', 'Frescor do Verão - 350 ml - Limão', 'PET', '350 ml','Limão',3.20)

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA])
VALUES
('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18)

-- ALTERE A EMBALAGEM DO ITEM 544931 PARA LATA E SEU PREÇO PARA 2.46. AJUSTE TAMBEM A EMEBALAGEM DO ITEM 1078680 PARA GARRAFA.
UPDATE [TABELA DE PRODUTOS]
SET EMBALAGEM = 'Lata',
	[PRECO DE LISTA] = 2.46
WHERE [CODIGO DO PRODUTO] = '544931'

UPDATE [TABELA DE PRODUTOS]
SET EMBALAGEM = 'Garrafa'
WHERE [CODIGO DO PRODUTO] = '1078680'

-- AULA 09 - EXERCICIO: ALTERANDO INFORMAÇÕES SOBRE OS VENDEDORES
-- ALTERE O A COMISSÃO DE 00235 PARA 11% E O NOME ADICIONE O SOBRENOME SOUSA AO NOME DO VENDEDOR 00236.
UPDATE [TABELA DE VENDEDORES]
SET [PERCENTUAL COMISSAO] = 0.11
WHERE MATRICULA = '00235'

UPDATE [TABELA DE VENDEDORES]
SET NOME = 'Claudia Morais Sousa'
WHERE MATRICULA = '00236'

-- AULAS 10 E 11: EXCLUINDO REGISTROS
-- VAMOS EXCLUIR UM DOS REGISTROS DA TABELA DE PRODUTOS.
DELETE FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO]='1078680'

DELETE FROM [TABELA DE VENDEDORES]
WHERE MATRICULA = '00235'


-- MÓDULO 06: ORDEM DOS CAMPOS E CHAVE PRIMARIA

-- AULAS 03 E 04: CHAVE PRIMARIA E CAMPOS NULOS
-- PARA TRANSFORMAR UM CAMPO EM PK É NECESSÁRIO QUE ELE NÃO ACEITE VALORES NULOS. 
-- VAMOS TORNAR O CAMPO 'MATRICULA', DA TABELA DE VENDEDORES, "NÃO ANULÁVEL" E DEPOIS VAMOS TORNÁ-LO A PK.

-- PASSO 1) PARA QUE NÃO SEJA ACEITA A INSERÇÃO DE VALORES NULO NO CAMPO:
ALTER TABLE [TABELA DE VENDEDORES]
ALTER COLUMN [MATRICULA]
VARCHAR(5) NOT NULL

-- PASSO 2) PARA TORNAR O CAMPO 'MATRICULA' A PK:
ALTER TABLE [TABELA DE VENDEDORES]
ADD CONSTRAINT PK_TABELA_DE_VENDEDORES
PRIMARY KEY CLUSTERED (MATRICULA)

-- AULA 09: MANIPULANDO TABELAS E CAMPOS LÓGICOS
-- VAMOS FAZER INSERIR UM REGISTRO NA TABELA DE CLIENTES COM A AJUDA DO  ASSISTENTE. FAÇA O SEGUINTE:
-- BOTÃO DIREITO DO MOUSE > 'SCRIPT DE TABELA COMO' > 'INSERT PARA' > 'ÁREA DE TRANSFERÊNCIA' > 
-- > COPIE ABAIXO O CÓDIGO QUE ESTÁ NA SUA ÁREA DE TRANSFERÊNCIA > EM 'VALUES' FAÇA A SUBSTITUIÇÃO DO TEXTO INSERINDO OS VALORES.
USE [SUCOS_VENDAS_REV2023]
GO

INSERT INTO [dbo].[TABELA DE CLIENTES]
           ([CPF]
           ,[NOME]
           ,[ENDERECO 1]
           ,[ENDERECO 2]
           ,[BAIRRO]
           ,[CIDADE]
           ,[ESTADO]
           ,[CEP]
           ,[DATA DE NASCIMENTO]
           ,[IDADE]
           ,[SEXO]
           ,[LIMITE DE CREDITO]
           ,[VOLUME DE COMPRA]
           ,[PRIMEIRA COMPRA])
     VALUES
           ('00383454802'
           ,'João da Silva'
           ,'Rua Projetada A'
           ,'Numero 233'
           ,'Copacabana'
           ,'Rio de Janeiro'
           ,'RJ'
           ,'20000000'
           ,'1965-03-21'  
           ,55
           ,'M'
           ,20000.00
           ,3000.23
           ,1)
GO


-- MÓDULO 07: CONSULTANDO DADOS DAS TABELAS

-- Aula 01: LISTANDO DADOS DA TABELA
-- VAMOS VER ALGUMAS FORMAS DE LISTAR CAMPOS DAS TABELAS:

-- 1) LISTANDO TODOS OS CAMPOS
SELECT [CPF]
      ,[NOME]
      ,[ENDERECO1]
      ,[ENDERECO2]
      ,[BAIRRO]
      ,[CIDADE]
      ,[ESTADO]
      ,[CEP]
      ,[DATA DE NASCIMENTO]
      ,[IDADE]
      ,[SEXO]
      ,[LIMITE DE CREDITO]
      ,[VOLUME DE COMPRA]
      ,[PRIMEIRA COMPRA]
  FROM [TABELA DE CLIENTES]

-- 2) LISTANDO TODOS OS CAMPOS USANDO *
SELECT * FROM [TABELA DE CLIENTES]

-- 3) LISTANDO CAMPOS ESPECÍFICOS
SELECT CPF, ENDERECO1
FROM [TABELA DE CLIENTES]

-- AULA 02: FILTRANDO REGISTRO
-- AS SELEÇÕES DO QUE DEVE SER EXIBIDO NÃO SE LIMITAM APENAS ÀS COLUNAS. PODEMOS INSERIR CONDIÇÕES BASEADAS NO VALOR DOS CAMPOS.
SELECT * FROM [TABELA DE PRODUTOS]
WHERE SABOR = 'Limão'

-- SELECIONADOS OS PRODUTOS DE SABOR LIMÃO, VAMOS AUMENTAR O PREÇO DELES EM 10%.
UPDATE [TABELA DE PRODUTOS]
SET [PRECO DE LISTA] = 1.1 * [PRECO DE LISTA]
WHERE SABOR = 'Limão'








