

-- MÓDULO 02: CONSULTANDO DADOS DE UMA TABELA

-- AULA 01: CONSULTA SIMPLES DE UMA TABELA
-- FAZENDO UM SELECT NA TABELA DE CLIENTES UTILIZANDO ALIAS 'TDC' EM VEZ DO NOME DA TABELA.
SELECT * FROM [TABELA_DE_CLIENTES] TDC;
SELECT TDC.CPF FROM TABELA_DE_CLIENTES TDC;

-- AULA 02: USANDO O LIKE
-- USANDO O LIKE PARA FAZER UMA CONSULTA QUE APRESENTE TODOS OS NOMES DE PRODUTOS TERMINADOS COM 'LIMAO'.
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Limao'

-- USANDO O 'LIKE' PARA FAZER UMA CONSULTA QUE APRESENTE TODOS OS PRODUTOS QUE CONTENHAM A PALAVRA 'MACA' NO NOME.
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Maca%'

-- USANDO O 'LIKE' PARA FAZER UMA CONSULTA QUE APRESENTE TODOS OS NOMES DE PRODUTOS INICIADOS COM 'MORANGO'.
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE 'Morango%'

-- REALIZANDO UMA CONSULTA UTILIZANDO 'LIKE', FUNÇÕES LÓGICAS E SUBSTITUINDO OS CAMPOS APRESENTADOS POR ALIAS.
SELECT CODIGO_DO_PRODUTO AS ID, NOME_DO_PRODUTO AS NOME, PRECO_DE_LISTA AS PRECO FROM TABELA_DE_PRODUTOS WHERE (SABOR LIKE '%Laranja%') AND (PRECO_DE_LISTA BETWEEN 7.50 AND 17.00)


-- MÓDULO 03: MUDANDO A APRESENTAÇÃO DOS DADOS DE UMA CONSULTA
